# Generated by Django 5.1 on 2025-05-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientoinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.IntegerField(help_text='Ingresa la cantidad según el tipo de movimiento:\n- Ingreso: cantidad a sumar al inventario.\n- Salida: cantidad a restar del inventario.\n- Ajuste: nuevo total exacto en inventario.'),
        ),
    ]
