# Generated by Django 5.1 on 2024-12-17 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('es_dama', models.BooleanField(default=False)),
                ('es_caballero', models.BooleanField(default=False)),
                ('es_unisex', models.BooleanField(default=False)),
                ('en_oferta', models.BooleanField(default=False)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tienda.categoria')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='tienda.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoTalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=False)),
                ('codigo_barras', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_tallas', to='tienda.producto')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_tallas', to='tienda.talla')),
            ],
            options={
                'unique_together': {('producto', 'talla')},
            },
        ),
    ]
