# Generated by Django 5.1 on 2024-12-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
