# Generated by Django 5.1 on 2025-01-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_imagen5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='es_caballero',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='es_dama',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='es_unisex',
        ),
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('unisex', 'Unisex'), ('no_especificado', 'No Especificado')], default='no_especificado', max_length=15),
        ),
    ]
