# Generated by Django 5.1 on 2025-01-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_producto_es_caballero_remove_producto_es_dama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='catalogo',
            field=models.CharField(choices=[('catalogo', 'Catálogo'), ('no_catalogo', 'No Catálogo')], default='no_catalogo', max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('caballero', 'Caballero'), ('dama', 'Dama'), ('unisex', 'Unisex'), ('no_especificado', 'No Especificado')], default='no_especificado', max_length=15),
        ),
    ]
