# Generated by Django 5.1 on 2025-02-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_producto_precio_alter_producto_precio_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='catalogo',
            field=models.CharField(choices=[('catalogo', 'En Catálogo'), ('no_catalogo', 'No Catálogo')], default='no_catalogo', max_length=15),
        ),
    ]
