# Generated by Django 5.1 on 2025-02-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_producto_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='catalogo',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('catalogo', 'En Catálogo'), ('no_catalogo', 'No Catálogo')], default='no_catalogo', max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('caballero', 'Caballero'), ('dama', 'Dama'), ('unisex', 'Unisex'), ('no_especificado', 'No Especificado')], default='no_especificado', max_length=15),
        ),
    ]
