# Generated by Django 5.1 on 2025-03-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_alter_producto_catalogo_alter_producto_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='provee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
