# Generated by Django 5.1 on 2025-03-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_proveedor_provee_alter_proveedor_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='provee',
            new_name='provedor_de',
        ),
    ]
