# Generated by Django 5.1 on 2025-03-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_rename_provee_proveedor_provedor_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
