# Generated by Django 5.1 on 2025-03-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_producto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción'), ('caballero', 'Caballero'), ('dama', 'Dama'), ('unisex', 'Unisex'), ('no_especificado', 'No Especificado')], max_length=15, null=True),
        ),
    ]
