# Generated by Django 5.1 on 2025-03-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_alter_producto_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción'), ('caballero', 'Caballero'), ('dama', 'Dama'), ('unisex', 'Unisex'), ('no_necesita', 'No necesita')], max_length=15, null=True),
        ),
    ]
