# Generated by Django 5.1 on 2025-03-31 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_alter_producto_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_venta',
        ),
    ]
