# Generated by Django 5.1 on 2025-04-06 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_rename_precio_producto_precio_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('codigo_hex', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='productotalla',
            name='genero',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción'), ('caballero', 'Caballero'), ('dama', 'Dama'), ('unisex', 'Unisex'), ('no_necesita', 'No necesita')], default='no_necesita', max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productotalla',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productotalla',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.color'),
        ),
        migrations.AlterUniqueTogether(
            name='productotalla',
            unique_together={('producto', 'talla', 'color', 'genero')},
        ),
    ]
