# Generated by Django 5.1 on 2025-04-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_color_productotalla_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='genero',
        ),
    ]
