# Generated by Django 5.1 on 2025-04-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_remove_producto_codigo_barras_remove_producto_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productotalla',
            name='activa',
        ),
    ]
