# Generated by Django 5.1 on 2025-04-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_remove_productotalla_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='productotalla',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
