# Generated by Django 5.1 on 2025-04-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0018_productotalla_activa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talla',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='color',
            name='codigo_hex',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='color',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un Producto con este Nombre.'}, max_length=100, unique=True),
        ),
    ]
