# Generated by Django 5.1 on 2025-04-12 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0021_generar_slugs_unicos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
    ]
