# Generated by Django 5.1 on 2025-02-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='facturado',
            field=models.BooleanField(default=False),
        ),
    ]
