# Generated by Django 5.1 on 2025-02-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_detalleventa_facturado_venta_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
