# Generated by Django 5.1 on 2025-02-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_venta_numero_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='iva',
        ),
    ]
