# Generated by Django 5.1 on 2025-04-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_venta_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
