# Generated by Django 5.1 on 2025-04-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_venta_anulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
