# Generated by Django 5.1 on 2025-05-07 20:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_detalleventa_anulado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('apertura', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo apertura')),
                ('gastos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total gastos')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
