# Generated by Django 5.1 on 2025-06-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata'), ('PSE', 'PSE'), ('TARJETA', 'Tarjeta de Crédito'), ('EFECTIVO', 'Efectivo'), ('ADDI', 'ADDI'), ('SISTECREDITO', 'Sistecredito')], default='EFECTIVO', max_length=25),
        ),
    ]
