# Generated by Django 5.1 on 2025-07-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_metodopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='facturada_electronicamente',
            field=models.BooleanField(default=False),
        ),
    ]
