# Generated by Django 5.1 on 2025-07-17 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0014_metodopago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=15)),
                ('razon_social', models.CharField(max_length=255)),
                ('certificado', models.FileField(upload_to='certificados/')),
                ('contrasena_certificado', models.CharField(max_length=100)),
                ('software_id', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('habilitado', models.BooleanField(default=True)),
                ('modo', models.CharField(choices=[('produccion', 'Producción'), ('pruebas', 'Pruebas')], default='produccion', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cufe', models.CharField(blank=True, max_length=100, null=True)),
                ('xml', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('rechazada', 'Rechazada'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('respuesta_dian', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura_electronica', to='ventas.venta')),
            ],
        ),
    ]
