# Generated by Django 5.1 on 2025-07-17 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionfacturaelectronica',
            options={'verbose_name': 'Configuración de Facturación Electrónica', 'verbose_name_plural': 'Configuraciones de Facturación Electrónica'},
        ),
        migrations.AlterModelOptions(
            name='facturaelectronica',
            options={'verbose_name': 'Factura Electrónica', 'verbose_name_plural': 'Facturas Electrónicas'},
        ),
        migrations.RemoveField(
            model_name='configuracionfacturaelectronica',
            name='cliente',
        ),
        migrations.AddField(
            model_name='configuracionfacturaelectronica',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracionfacturaelectronica',
            name='certificado',
            field=models.FileField(upload_to='certificados/', verbose_name='Certificado Digital (.p12)'),
        ),
        migrations.AlterField(
            model_name='configuracionfacturaelectronica',
            name='contrasena_certificado',
            field=models.CharField(max_length=100, verbose_name='Contraseña del Certificado'),
        ),
        migrations.AlterField(
            model_name='configuracionfacturaelectronica',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='¿Habilitado para Facturación?'),
        ),
        migrations.AlterField(
            model_name='configuracionfacturaelectronica',
            name='modo',
            field=models.CharField(choices=[('produccion', 'Producción'), ('pruebas', 'Pruebas')], default='produccion', max_length=20, verbose_name='Modo DIAN'),
        ),
        migrations.AlterField(
            model_name='configuracionfacturaelectronica',
            name='nit',
            field=models.CharField(max_length=15, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='configuracionfacturaelectronica',
            name='pin',
            field=models.CharField(max_length=10, verbose_name='PIN del Software'),
        ),
        migrations.AlterField(
            model_name='configuracionfacturaelectronica',
            name='razon_social',
            field=models.CharField(max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='configuracionfacturaelectronica',
            name='software_id',
            field=models.CharField(max_length=100, verbose_name='Software ID'),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío'),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='numero_cufe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CUFE'),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='respuesta_dian',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta DIAN'),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='xml',
            field=models.TextField(blank=True, null=True, verbose_name='XML generado'),
        ),
    ]
