# Generated by Django 5.1 on 2025-03-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('gerente', 'Gerente'), ('vendedor', 'Vendedor')], max_length=20),
        ),
    ]
